import beginners from '@/images/UOC aloittelijoille.png'

export const projects = [
    {
        title: "Projekti 1",
    },
    {
        title: "Projekti 2",
    },
    {
        title: "Projekti 3",
    },
    {
        title: "Projekti 4",
    },
    {
        title: "Projekti 5",
    },
    {
        title: "Projekti 6",
    },
    {
        title: "Projekti 7",
    },
    {
        title: "Projekti 8",
    },
]

export const user = [
    {
        name: "Sutigit",
        id: 1,
    }
]

export const githubAccounts = [
    {
        login: "sutigit",
        id: 117278596,
        node_id: "U_kgDOBv2HhA",
        avatar_url: "https://avatars.githubusercontent.com/u/117278596?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/sutigit",
        html_url: "https://github.com/sutigit",
        followers_url: "https://api.github.com/users/sutigit/followers",
        following_url: "https://api.github.com/users/sutigit/following{/other_user}",
        gists_url: "https://api.github.com/users/sutigit/gists{/gist_id}",
        starred_url: "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/sutigit/subscriptions",
        organizations_url: "https://api.github.com/users/sutigit/orgs",
        repos_url: "https://api.github.com/users/sutigit/repos",
        events_url: "https://api.github.com/users/sutigit/events{/privacy}",
        received_events_url: "https://api.github.com/users/sutigit/received_events",
        type: "User",
        site_admin: false,
        name: "Ben Panyanil",
        company: null,
        blog: "",
        location: "Helsinki",
        email: null,
        hireable: null,
        bio: "Computer science student at Helsinki university",
        twitter_username: null,
        public_repos: 23,
        public_gists: 0,
        followers: 4,
        following: 4,
        created_at: "2022-11-02T11:43:57Z",
        updated_at: "2024-07-19T11:12:54Z"
    },
    {
        login: "tiigit",
        id: 116378573,
        node_id: "U_kgDOBu_LzQ",
        avatar_url: "https://avatars.githubusercontent.com/u/116378573?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/tiigit",
        html_url: "https://github.com/tiigit",
        followers_url: "https://api.github.com/users/tiigit/followers",
        following_url: "https://api.github.com/users/tiigit/following{/other_user}",
        gists_url: "https://api.github.com/users/tiigit/gists{/gist_id}",
        starred_url: "https://api.github.com/users/tiigit/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/tiigit/subscriptions",
        organizations_url: "https://api.github.com/users/tiigit/orgs",
        repos_url: "https://api.github.com/users/tiigit/repos",
        events_url: "https://api.github.com/users/tiigit/events{/privacy}",
        received_events_url: "https://api.github.com/users/tiigit/received_events",
        type: "User",
        site_admin: false,
        name: "Tiia Poikajärvi",
        company: null,
        blog: "",
        location: null,
        email: null,
        hireable: null,
        bio: "Linguistics (Language Technology) Student at University of Helsinki",
        twitter_username: null,
        public_repos: 2,
        public_gists: 0,
        followers: 2,
        following: 2,
        created_at: "2022-10-21T16:58:05Z",
        updated_at: "2024-06-06T18:57:01Z"
    }
]

export const categories = [
    {
        title: "Aloittelijoille",
        img: beginners,
        numberOfProjects: 5
    },
    {
        title: "Haastetta",
        img: beginners,
        numberOfProjects: 3
    },
    {
        title: "Pelejä",
        img: beginners,
        numberOfProjects: 1
    },
    {
        title: "Tekoäly",
        img: beginners,
        numberOfProjects: 5
    },
    {
        title: "Web Sovellukset",
        img: beginners,
        numberOfProjects: 3
    },
    {
        title: "Mobiili Sovellukset",
        img: beginners,
        numberOfProjects: 1
    },
    {
        title: "Muuta",
        img: beginners,
        numberOfProjects: 5
    },
]

export const frontPageTabs = [
    {
        id: 1,
        label: "Esittelyssä",
    },
    {
        id: 2,
        label: "Kaikki",
    },
    {
        id: 3,
        label: "Sinulle",
    },
]

export const repositories = [
    {
      "id": 576562220,
      "node_id": "R_kgDOIl2kLA",
      "name": "daily-writings-app",
      "full_name": "sutigit/daily-writings-app",
      "private": false,
      "owner": {
        "login": "sutigit",
        "id": 117278596,
        "node_id": "U_kgDOBv2HhA",
        "avatar_url": "https://avatars.githubusercontent.com/u/117278596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sutigit",
        "html_url": "https://github.com/sutigit",
        "followers_url": "https://api.github.com/users/sutigit/followers",
        "following_url": "https://api.github.com/users/sutigit/following{/other_user}",
        "gists_url": "https://api.github.com/users/sutigit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sutigit/subscriptions",
        "organizations_url": "https://api.github.com/users/sutigit/orgs",
        "repos_url": "https://api.github.com/users/sutigit/repos",
        "events_url": "https://api.github.com/users/sutigit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sutigit/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/sutigit/daily-writings-app",
      "description": "This app generates a new markdown file for diary writings for that current date the app is invoked.",
      "fork": false,
      "url": "https://api.github.com/repos/sutigit/daily-writings-app",
      "forks_url": "https://api.github.com/repos/sutigit/daily-writings-app/forks",
      "keys_url": "https://api.github.com/repos/sutigit/daily-writings-app/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/sutigit/daily-writings-app/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/sutigit/daily-writings-app/teams",
      "hooks_url": "https://api.github.com/repos/sutigit/daily-writings-app/hooks",
      "issue_events_url": "https://api.github.com/repos/sutigit/daily-writings-app/issues/events{/number}",
      "events_url": "https://api.github.com/repos/sutigit/daily-writings-app/events",
      "assignees_url": "https://api.github.com/repos/sutigit/daily-writings-app/assignees{/user}",
      "branches_url": "https://api.github.com/repos/sutigit/daily-writings-app/branches{/branch}",
      "tags_url": "https://api.github.com/repos/sutigit/daily-writings-app/tags",
      "blobs_url": "https://api.github.com/repos/sutigit/daily-writings-app/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/sutigit/daily-writings-app/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/sutigit/daily-writings-app/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/sutigit/daily-writings-app/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/sutigit/daily-writings-app/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/sutigit/daily-writings-app/languages",
      "stargazers_url": "https://api.github.com/repos/sutigit/daily-writings-app/stargazers",
      "contributors_url": "https://api.github.com/repos/sutigit/daily-writings-app/contributors",
      "subscribers_url": "https://api.github.com/repos/sutigit/daily-writings-app/subscribers",
      "subscription_url": "https://api.github.com/repos/sutigit/daily-writings-app/subscription",
      "commits_url": "https://api.github.com/repos/sutigit/daily-writings-app/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/sutigit/daily-writings-app/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/sutigit/daily-writings-app/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/sutigit/daily-writings-app/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/sutigit/daily-writings-app/contents/{+path}",
      "compare_url": "https://api.github.com/repos/sutigit/daily-writings-app/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/sutigit/daily-writings-app/merges",
      "archive_url": "https://api.github.com/repos/sutigit/daily-writings-app/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/sutigit/daily-writings-app/downloads",
      "issues_url": "https://api.github.com/repos/sutigit/daily-writings-app/issues{/number}",
      "pulls_url": "https://api.github.com/repos/sutigit/daily-writings-app/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/sutigit/daily-writings-app/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/sutigit/daily-writings-app/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/sutigit/daily-writings-app/labels{/name}",
      "releases_url": "https://api.github.com/repos/sutigit/daily-writings-app/releases{/id}",
      "deployments_url": "https://api.github.com/repos/sutigit/daily-writings-app/deployments",
      "created_at": "2022-12-10T08:29:30Z",
      "updated_at": "2022-12-10T09:21:43Z",
      "pushed_at": "2022-12-11T13:40:09Z",
      "git_url": "git://github.com/sutigit/daily-writings-app.git",
      "ssh_url": "git@github.com:sutigit/daily-writings-app.git",
      "clone_url": "https://github.com/sutigit/daily-writings-app.git",
      "svn_url": "https://github.com/sutigit/daily-writings-app",
      "homepage": null,
      "size": 24,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "Python",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 1,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
  
      ],
      "visibility": "public",
      "forks": 1,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main"
    },
    {
      "id": 616667837,
      "node_id": "R_kgDOJMGavQ",
      "name": "electron-template",
      "full_name": "sutigit/electron-template",
      "private": false,
      "owner": {
        "login": "sutigit",
        "id": 117278596,
        "node_id": "U_kgDOBv2HhA",
        "avatar_url": "https://avatars.githubusercontent.com/u/117278596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sutigit",
        "html_url": "https://github.com/sutigit",
        "followers_url": "https://api.github.com/users/sutigit/followers",
        "following_url": "https://api.github.com/users/sutigit/following{/other_user}",
        "gists_url": "https://api.github.com/users/sutigit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sutigit/subscriptions",
        "organizations_url": "https://api.github.com/users/sutigit/orgs",
        "repos_url": "https://api.github.com/users/sutigit/repos",
        "events_url": "https://api.github.com/users/sutigit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sutigit/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/sutigit/electron-template",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/sutigit/electron-template",
      "forks_url": "https://api.github.com/repos/sutigit/electron-template/forks",
      "keys_url": "https://api.github.com/repos/sutigit/electron-template/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/sutigit/electron-template/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/sutigit/electron-template/teams",
      "hooks_url": "https://api.github.com/repos/sutigit/electron-template/hooks",
      "issue_events_url": "https://api.github.com/repos/sutigit/electron-template/issues/events{/number}",
      "events_url": "https://api.github.com/repos/sutigit/electron-template/events",
      "assignees_url": "https://api.github.com/repos/sutigit/electron-template/assignees{/user}",
      "branches_url": "https://api.github.com/repos/sutigit/electron-template/branches{/branch}",
      "tags_url": "https://api.github.com/repos/sutigit/electron-template/tags",
      "blobs_url": "https://api.github.com/repos/sutigit/electron-template/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/sutigit/electron-template/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/sutigit/electron-template/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/sutigit/electron-template/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/sutigit/electron-template/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/sutigit/electron-template/languages",
      "stargazers_url": "https://api.github.com/repos/sutigit/electron-template/stargazers",
      "contributors_url": "https://api.github.com/repos/sutigit/electron-template/contributors",
      "subscribers_url": "https://api.github.com/repos/sutigit/electron-template/subscribers",
      "subscription_url": "https://api.github.com/repos/sutigit/electron-template/subscription",
      "commits_url": "https://api.github.com/repos/sutigit/electron-template/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/sutigit/electron-template/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/sutigit/electron-template/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/sutigit/electron-template/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/sutigit/electron-template/contents/{+path}",
      "compare_url": "https://api.github.com/repos/sutigit/electron-template/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/sutigit/electron-template/merges",
      "archive_url": "https://api.github.com/repos/sutigit/electron-template/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/sutigit/electron-template/downloads",
      "issues_url": "https://api.github.com/repos/sutigit/electron-template/issues{/number}",
      "pulls_url": "https://api.github.com/repos/sutigit/electron-template/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/sutigit/electron-template/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/sutigit/electron-template/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/sutigit/electron-template/labels{/name}",
      "releases_url": "https://api.github.com/repos/sutigit/electron-template/releases{/id}",
      "deployments_url": "https://api.github.com/repos/sutigit/electron-template/deployments",
      "created_at": "2023-03-20T20:55:30Z",
      "updated_at": "2023-03-20T20:55:36Z",
      "pushed_at": "2023-03-20T20:58:49Z",
      "git_url": "git://github.com/sutigit/electron-template.git",
      "ssh_url": "git@github.com:sutigit/electron-template.git",
      "clone_url": "https://github.com/sutigit/electron-template.git",
      "svn_url": "https://github.com/sutigit/electron-template",
      "homepage": null,
      "size": 12,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
  
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master"
    },
    {
      "id": 827959397,
      "node_id": "R_kgDOMVmoZQ",
      "name": "first-contributions",
      "full_name": "sutigit/first-contributions",
      "private": false,
      "owner": {
        "login": "sutigit",
        "id": 117278596,
        "node_id": "U_kgDOBv2HhA",
        "avatar_url": "https://avatars.githubusercontent.com/u/117278596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sutigit",
        "html_url": "https://github.com/sutigit",
        "followers_url": "https://api.github.com/users/sutigit/followers",
        "following_url": "https://api.github.com/users/sutigit/following{/other_user}",
        "gists_url": "https://api.github.com/users/sutigit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sutigit/subscriptions",
        "organizations_url": "https://api.github.com/users/sutigit/orgs",
        "repos_url": "https://api.github.com/users/sutigit/repos",
        "events_url": "https://api.github.com/users/sutigit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sutigit/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/sutigit/first-contributions",
      "description": "🚀✨ Help beginners to contribute to open source projects",
      "fork": true,
      "url": "https://api.github.com/repos/sutigit/first-contributions",
      "forks_url": "https://api.github.com/repos/sutigit/first-contributions/forks",
      "keys_url": "https://api.github.com/repos/sutigit/first-contributions/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/sutigit/first-contributions/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/sutigit/first-contributions/teams",
      "hooks_url": "https://api.github.com/repos/sutigit/first-contributions/hooks",
      "issue_events_url": "https://api.github.com/repos/sutigit/first-contributions/issues/events{/number}",
      "events_url": "https://api.github.com/repos/sutigit/first-contributions/events",
      "assignees_url": "https://api.github.com/repos/sutigit/first-contributions/assignees{/user}",
      "branches_url": "https://api.github.com/repos/sutigit/first-contributions/branches{/branch}",
      "tags_url": "https://api.github.com/repos/sutigit/first-contributions/tags",
      "blobs_url": "https://api.github.com/repos/sutigit/first-contributions/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/sutigit/first-contributions/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/sutigit/first-contributions/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/sutigit/first-contributions/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/sutigit/first-contributions/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/sutigit/first-contributions/languages",
      "stargazers_url": "https://api.github.com/repos/sutigit/first-contributions/stargazers",
      "contributors_url": "https://api.github.com/repos/sutigit/first-contributions/contributors",
      "subscribers_url": "https://api.github.com/repos/sutigit/first-contributions/subscribers",
      "subscription_url": "https://api.github.com/repos/sutigit/first-contributions/subscription",
      "commits_url": "https://api.github.com/repos/sutigit/first-contributions/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/sutigit/first-contributions/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/sutigit/first-contributions/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/sutigit/first-contributions/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/sutigit/first-contributions/contents/{+path}",
      "compare_url": "https://api.github.com/repos/sutigit/first-contributions/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/sutigit/first-contributions/merges",
      "archive_url": "https://api.github.com/repos/sutigit/first-contributions/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/sutigit/first-contributions/downloads",
      "issues_url": "https://api.github.com/repos/sutigit/first-contributions/issues{/number}",
      "pulls_url": "https://api.github.com/repos/sutigit/first-contributions/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/sutigit/first-contributions/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/sutigit/first-contributions/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/sutigit/first-contributions/labels{/name}",
      "releases_url": "https://api.github.com/repos/sutigit/first-contributions/releases{/id}",
      "deployments_url": "https://api.github.com/repos/sutigit/first-contributions/deployments",
      "created_at": "2024-07-12T18:54:02Z",
      "updated_at": "2024-07-12T18:54:02Z",
      "pushed_at": "2024-07-12T19:05:10Z",
      "git_url": "git://github.com/sutigit/first-contributions.git",
      "ssh_url": "git@github.com:sutigit/first-contributions.git",
      "clone_url": "https://github.com/sutigit/first-contributions.git",
      "svn_url": "https://github.com/sutigit/first-contributions",
      "homepage": "https://firstcontributions.github.io",
      "size": 43296,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": null,
      "has_issues": false,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
  
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main"
    },
    {
      "id": 639975583,
      "node_id": "R_kgDOJiVAnw",
      "name": "Fullstack-open",
      "full_name": "sutigit/Fullstack-open",
      "private": false,
      "owner": {
        "login": "sutigit",
        "id": 117278596,
        "node_id": "U_kgDOBv2HhA",
        "avatar_url": "https://avatars.githubusercontent.com/u/117278596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sutigit",
        "html_url": "https://github.com/sutigit",
        "followers_url": "https://api.github.com/users/sutigit/followers",
        "following_url": "https://api.github.com/users/sutigit/following{/other_user}",
        "gists_url": "https://api.github.com/users/sutigit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sutigit/subscriptions",
        "organizations_url": "https://api.github.com/users/sutigit/orgs",
        "repos_url": "https://api.github.com/users/sutigit/repos",
        "events_url": "https://api.github.com/users/sutigit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sutigit/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/sutigit/Fullstack-open",
      "description": "exercise submissions from MOOC Fullstack-open 2023",
      "fork": false,
      "url": "https://api.github.com/repos/sutigit/Fullstack-open",
      "forks_url": "https://api.github.com/repos/sutigit/Fullstack-open/forks",
      "keys_url": "https://api.github.com/repos/sutigit/Fullstack-open/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/sutigit/Fullstack-open/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/sutigit/Fullstack-open/teams",
      "hooks_url": "https://api.github.com/repos/sutigit/Fullstack-open/hooks",
      "issue_events_url": "https://api.github.com/repos/sutigit/Fullstack-open/issues/events{/number}",
      "events_url": "https://api.github.com/repos/sutigit/Fullstack-open/events",
      "assignees_url": "https://api.github.com/repos/sutigit/Fullstack-open/assignees{/user}",
      "branches_url": "https://api.github.com/repos/sutigit/Fullstack-open/branches{/branch}",
      "tags_url": "https://api.github.com/repos/sutigit/Fullstack-open/tags",
      "blobs_url": "https://api.github.com/repos/sutigit/Fullstack-open/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/sutigit/Fullstack-open/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/sutigit/Fullstack-open/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/sutigit/Fullstack-open/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/sutigit/Fullstack-open/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/sutigit/Fullstack-open/languages",
      "stargazers_url": "https://api.github.com/repos/sutigit/Fullstack-open/stargazers",
      "contributors_url": "https://api.github.com/repos/sutigit/Fullstack-open/contributors",
      "subscribers_url": "https://api.github.com/repos/sutigit/Fullstack-open/subscribers",
      "subscription_url": "https://api.github.com/repos/sutigit/Fullstack-open/subscription",
      "commits_url": "https://api.github.com/repos/sutigit/Fullstack-open/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/sutigit/Fullstack-open/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/sutigit/Fullstack-open/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/sutigit/Fullstack-open/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/sutigit/Fullstack-open/contents/{+path}",
      "compare_url": "https://api.github.com/repos/sutigit/Fullstack-open/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/sutigit/Fullstack-open/merges",
      "archive_url": "https://api.github.com/repos/sutigit/Fullstack-open/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/sutigit/Fullstack-open/downloads",
      "issues_url": "https://api.github.com/repos/sutigit/Fullstack-open/issues{/number}",
      "pulls_url": "https://api.github.com/repos/sutigit/Fullstack-open/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/sutigit/Fullstack-open/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/sutigit/Fullstack-open/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/sutigit/Fullstack-open/labels{/name}",
      "releases_url": "https://api.github.com/repos/sutigit/Fullstack-open/releases{/id}",
      "deployments_url": "https://api.github.com/repos/sutigit/Fullstack-open/deployments",
      "created_at": "2023-05-12T17:02:28Z",
      "updated_at": "2023-05-15T11:27:59Z",
      "pushed_at": "2023-07-28T13:23:08Z",
      "git_url": "git://github.com/sutigit/Fullstack-open.git",
      "ssh_url": "git@github.com:sutigit/Fullstack-open.git",
      "clone_url": "https://github.com/sutigit/Fullstack-open.git",
      "svn_url": "https://github.com/sutigit/Fullstack-open",
      "homepage": null,
      "size": 4964,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
  
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main"
    },
    {
      "id": 673015427,
      "node_id": "R_kgDOKB1mgw",
      "name": "Fullstack-open-part1",
      "full_name": "sutigit/Fullstack-open-part1",
      "private": false,
      "owner": {
        "login": "sutigit",
        "id": 117278596,
        "node_id": "U_kgDOBv2HhA",
        "avatar_url": "https://avatars.githubusercontent.com/u/117278596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sutigit",
        "html_url": "https://github.com/sutigit",
        "followers_url": "https://api.github.com/users/sutigit/followers",
        "following_url": "https://api.github.com/users/sutigit/following{/other_user}",
        "gists_url": "https://api.github.com/users/sutigit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sutigit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sutigit/subscriptions",
        "organizations_url": "https://api.github.com/users/sutigit/orgs",
        "repos_url": "https://api.github.com/users/sutigit/repos",
        "events_url": "https://api.github.com/users/sutigit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sutigit/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/sutigit/Fullstack-open-part1",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/sutigit/Fullstack-open-part1",
      "forks_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/forks",
      "keys_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/teams",
      "hooks_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/hooks",
      "issue_events_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/issues/events{/number}",
      "events_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/events",
      "assignees_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/assignees{/user}",
      "branches_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/branches{/branch}",
      "tags_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/tags",
      "blobs_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/languages",
      "stargazers_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/stargazers",
      "contributors_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/contributors",
      "subscribers_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/subscribers",
      "subscription_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/subscription",
      "commits_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/contents/{+path}",
      "compare_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/merges",
      "archive_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/downloads",
      "issues_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/issues{/number}",
      "pulls_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/labels{/name}",
      "releases_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/releases{/id}",
      "deployments_url": "https://api.github.com/repos/sutigit/Fullstack-open-part1/deployments",
      "created_at": "2023-07-31T17:13:17Z",
      "updated_at": "2023-07-31T17:13:23Z",
      "pushed_at": "2023-07-31T17:13:19Z",
      "git_url": "git://github.com/sutigit/Fullstack-open-part1.git",
      "ssh_url": "git@github.com:sutigit/Fullstack-open-part1.git",
      "clone_url": "https://github.com/sutigit/Fullstack-open-part1.git",
      "svn_url": "https://github.com/sutigit/Fullstack-open-part1",
      "homepage": null,
      "size": 170,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
  
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main"
    },
]

export const projectDescriptionHelpers = [
    {
        label: 'Aloittelija ystävällinen',
        color: 'bg-yellow-300',
    },
    {
        label: 'Kaikille',
        color: 'bg-blue-300',
    },
    {
        label: 'Kokeilu',
        color: 'bg-orange-300',
    },
    {
        label: 'Peli',
        color: 'bg-lime-300',
    },
    {
        label: 'Apua',
        color: 'bg-fuchsia-300',
    }
]